### ISSUE TITLE
File Not Found Error due to missing folders in the dataset

### ISSUE THREAD

**Issue by souvik0306** [lukaskondmann/SiROC#1]
Hi! 
I'm trying to implement the **[Spatial Context Awareness for Unsupervised Change Detection in Optical Satellite Images](https://arxiv.org/pdf/2110.02068.pdf)** for a Remote Sensing Application involving change detection.

I have downloaded the required **Onera Satellite Change Detection Dataset** from - [IEEE Dataport](https://ieee-dataport.org/open-access/oscd-onera-satellite-change-detection) as specified. 

The [README.d](https://github.com/lukaskondmann/SiROC#evaluation-of-siroc) of the repository states that only `data_path` and `out_dir` are to be modified as per user in order to run `train.py`. 

Here are the `data_path` and `out_dir` file paths as per my system - 

    data_path = r'SiROC\Onera Satellite Change Detection dataset - Images'
    out_dir = r'SiROC\Results_save'
### The Folder Structure used -
    .
    ├── SiROC                   
    │   ├── data          
    │   ├── train.py
    │   ├── method.py  
    │   ├── metrics.py   
    │   ├── requirements.txt
    │   ├── Results_save
    │   ├── README.md           
    │   └── Onera Satellite Change Detection dataset - Images  

On executing as specified I encountered the following error- 

     FileNotFoundError: [Errno 2] No such file or directory: 'D:\\SiROC\\Onera Satellite Change Detection dataset - 
     ImagesOnera\\splits\\test.txt'`
 
I have further inspected the dataset but there is neither any `Onera sub-folder` nor any `splits`  sub-folder init, the `test.txt` and `train.txt` are in the main `Onera Satellite Change Detection dataset - Images` folder and not in any of the provided sub-folders.  

Does one need to modify the Dataset structure to run the **_train.py_** code? Please provide adequate insight on this issue

**Comment by lukaskondmann** [comment]
Hi, 

I looked into this and given the current format on IEEE port the train.txt and test.txt file indeed have to be moved into a new folder "splits". I specified this in the readme now. Thanks for the pointer!
